[Refactoring] 카카오디자인 최종 및 로그인 실패시 나오는 alert 리펙토링
APP-iOS3rd/PJ3T2_Mymory pull request #141
Opened 2024-01-31 06:11 UTC by Ahario

# PR 가이드라인
## PR Checklist
PR 날릴 때 체크 리스트

- [ ] 코드 컨벤션을 잘 지키셨나요?
- [ ] 이슈 체크리스트를 잘 반영했나요?
- [ ] Conflict 문제가 발생하지는 않나요?

## PR Type
어떤 종류의 PR인가요?

- [ ] 버그 수정
- [ ] 새 기능 개발
- [ ] 코드 스타일 변경
- [ ] 리팩토링
- [ ] 문서 작업 변경
- [ ] 기타 작업

## 연관되는 issue 정보를 알려주세요

Issue Number: N/A

# PR 설명하기
[Add]
카카오로그인 버튼 디자인을 카카오 공식 가이드에 맞게 수정하였습니다. 기존의 노란색이 아닌 KakaoYellow라는 색상을 추가하였습니다. 
기존의 LoginWithKakao 문구를 카카오 로그인으로 수정하였습니다.

[Refactoring]
명섭님과 상의한결과 명섭님의 로그인 실패시 나오는 alert를 사용하기로했습니다. 같은 부분을 수정할경우 깃에러가 나기에, 제 부분을 원래 develop상태로 되돌렸습니다.

---

## 기타 언급해야 할 사항들

- 간단한 디자인 변경이기에 코드첨부나 스크린샷은 생략하겠습니다

2024-01-31 06:13 UTC, Ahario commented
현재로써 카카오로그인은 더이상 기능추가가 불가능해서, 머지 후 브랜치를 닫아주시면 감사하겠습니다.

2024-01-31 07:22 UTC, Seobe95 commented on MyMemory/MyMemory.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
이부분은 머지되어도 괜찮은 건가요? conflict가 난 상태로 올라온 것 같습니다

2024-01-31 08:17 UTC, iAmSomething requested changes
Package.resolved 여기를 없애서 올려주세요

2024-02-01 00:53 UTC, Ahario commented
컨플릭 해결한것같습니다. 태훈님이 알려주신 파일 들어가보니까 sdk가 업데이트가 되는과정에서 컨플릭이 난것같아서, 지우는것보다 디벨롤과 똑같이 만드는식으로 해결했습니다. 그외 로그인뷰에서 실수로 지운 코드들고 복구했습니다

2024-02-01 01:20 UTC, iAmSomething approved these changes

2024-02-01 01:21 UTC, Seobe95 approved these changes
고생하셨습니당

2024-02-01 04:57 UTC, jeonguk29 reviewed
고생 하셨습니다 ㅠㅠ

2024-02-01 05:00 UTC, merged